import { ItemDefinition } from '../gameTypes';

export const ARMOR_ITEMS: ItemDefinition[] = [
  {
    id: 'leather_helmet',
    name: 'Leather Cap',
    description: 'Basic head protection.',
    type: 'armor',
    rarity: 'common',
    sellPrice: 10,
    stackable: false,
    maxStack: 1,
    icon: 'leather_helmet',
    armorSlot: 'helmet',
    stats: { armor: 1, durability: 55 },
  },
  {
    id: 'leather_chestplate',
    name: 'Leather Tunic',
    description: 'Basic body protection.',
    type: 'armor',
    rarity: 'common',
    sellPrice: 16,
    stackable: false,
    maxStack: 1,
    icon: 'leather_chestplate',
    armorSlot: 'chestplate',
    stats: { armor: 3, durability: 80 },
  },
  {
    id: 'iron_helmet',
    name: 'Iron Helmet',
    description: 'Solid iron head protection.',
    type: 'armor',
    rarity: 'uncommon',
    sellPrice: 40,
    stackable: false,
    maxStack: 1,
    icon: 'iron_helmet',
    armorSlot: 'helmet',
    stats: { armor: 2, durability: 165 },
  },
  {
    id: 'iron_chestplate',
    name: 'Iron Chestplate',
    description: 'Heavy iron body armor.',
    type: 'armor',
    rarity: 'uncommon',
    sellPrice: 64,
    stackable: false,
    maxStack: 1,
    icon: 'iron_chestplate',
    armorSlot: 'chestplate',
    stats: { armor: 6, durability: 240 },
  },
  {
    id: 'diamond_helmet',
    name: 'Diamond Helmet',
    description: 'Premium diamond headgear.',
    type: 'armor',
    rarity: 'epic',
    sellPrice: 300,
    stackable: false,
    maxStack: 1,
    icon: 'diamond_helmet',
    armorSlot: 'helmet',
    stats: { armor: 3, toughness: 2, durability: 363 },
  },
  {
    id: 'diamond_chestplate',
    name: 'Diamond Chestplate',
    description: 'Superior diamond body armor.',
    type: 'armor',
    rarity: 'epic',
    sellPrice: 480,
    stackable: false,
    maxStack: 1,
    icon: 'diamond_chestplate',
    armorSlot: 'chestplate',
    stats: { armor: 8, toughness: 2, durability: 528 },
  },
  {
    id: 'netherite_chestplate',
    name: 'Netherite Chestplate',
    description: 'Ultimate protection. Forged in the Nether.',
    type: 'armor',
    rarity: 'legendary',
    sellPrice: 1500,
    stackable: false,
    maxStack: 1,
    icon: 'netherite_chestplate',
    armorSlot: 'chestplate',
    stats: { armor: 8, toughness: 3, knockback_resistance: 1, durability: 592 },
  },
];
