import { ItemDefinition } from '../gameTypes';

export const BLOCK_ITEMS: ItemDefinition[] = [
  {
    id: 'cobblestone',
    name: 'Cobblestone',
    description: 'A rough block of stone. Common building material.',
    type: 'block',
    rarity: 'common',
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: 'cobblestone',
  },
  {
    id: 'stone',
    name: 'Stone',
    description: 'Smooth stone block. Smelted from cobblestone.',
    type: 'block',
    rarity: 'common',
    sellPrice: 2,
    stackable: true,
    maxStack: 64,
    icon: 'stone',
  },
  {
    id: 'oak_log',
    name: 'Oak Log',
    description: 'A log of oak wood. Versatile material.',
    type: 'block',
    rarity: 'common',
    sellPrice: 3,
    stackable: true,
    maxStack: 64,
    icon: 'oak_log',
  },
  {
    id: 'oak_planks',
    name: 'Oak Planks',
    description: 'Wooden planks crafted from oak logs.',
    type: 'block',
    rarity: 'common',
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: 'oak_planks',
  },
  {
    id: 'dirt',
    name: 'Dirt',
    description: 'Basic soil block. Good for farming.',
    type: 'block',
    rarity: 'common',
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: 'dirt',
  },
  {
    id: 'sand',
    name: 'Sand',
    description: 'Grainy block. Can be smelted into glass.',
    type: 'block',
    rarity: 'common',
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: 'sand',
  },
  {
    id: 'gravel',
    name: 'Gravel',
    description: 'Loose rocky block. May contain flint.',
    type: 'block',
    rarity: 'common',
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: 'gravel',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Extremely hard volcanic glass. Nearly indestructible.',
    type: 'block',
    rarity: 'epic',
    sellPrice: 50,
    stackable: true,
    maxStack: 64,
    icon: 'obsidian',
  },
];
