import { ItemDefinition } from "../gameTypes";

export const FOOD_ITEMS: ItemDefinition[] = [
  {
    id: "apple",
    name: "Apple",
    description: "Fresh red apple. Restores hunger.",
    type: "food",
    rarity: "common",
    sellPrice: 2,
    stackable: true,
    maxStack: 64,
    icon: "apple.png",
    stats: { hunger: 4, saturation: 2.4 },
  },
  {
    id: "bread",
    name: "Bread",
    description: "Baked from wheat. Basic food source.",
    type: "food",
    rarity: "common",
    sellPrice: 3,
    stackable: true,
    maxStack: 64,
    icon: "bread.png",
    stats: { hunger: 5, saturation: 6 },
    recipe: {
      resultQuantity: 1,
      ingredients: [{ itemId: "wheat", quantity: 3 }],
      craftTime: 3000,
      category: "food",
    },
  },
  {
    id: "steak",
    name: "Steak",
    description: "Steak! Highly nutritious.",
    type: "food",
    rarity: "uncommon",
    sellPrice: 8,
    stackable: true,
    maxStack: 64,
    icon: "steak.png",
    stats: { hunger: 8, saturation: 12.8 },
  },
  {
    id: "golden_apple",
    name: "Golden Apple",
    description: "Enchanted apple with golden coating.",
    type: "food",
    rarity: "rare",
    sellPrice: 50,
    stackable: true,
    maxStack: 64,
    icon: "gold_apple.png",
    stats: { hunger: 4, saturation: 9.6, absorption: 2 },
    recipe: {
      resultQuantity: 1,
      ingredients: [
        { itemId: "apple", quantity: 1 },
        { itemId: "gold_ingot", quantity: 8 },
      ],
      craftTime: 10000,
      category: "food",
    },
  },
  {
    id: "enchanted_golden_apple",
    name: "Enchanted Golden Apple",
    description: "Legendary apple of the gods.",
    type: "food",
    rarity: "legendary",
    sellPrice: 500,
    stackable: true,
    maxStack: 64,
    icon: "enchanted_golden_apple",
    stats: { hunger: 4, saturation: 9.6, absorption: 4, regeneration: 2 },
  },
];
