import { ItemDefinition } from '../gameTypes';

export const MATERIAL_ITEMS: ItemDefinition[] = [
  {
    id: 'stick',
    name: 'Stick',
    description: 'Wooden stick. Basic crafting component.',
    type: 'material',
    rarity: 'common',
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: 'stick',
  },
  {
    id: 'string',
    name: 'String',
    description: 'Spider silk thread. Used for bows and fishing.',
    type: 'material',
    rarity: 'common',
    sellPrice: 3,
    stackable: true,
    maxStack: 64,
    icon: 'string',
  },
  {
    id: 'leather',
    name: 'Leather',
    description: 'Animal hide. Used for armor and books.',
    type: 'material',
    rarity: 'common',
    sellPrice: 5,
    stackable: true,
    maxStack: 64,
    icon: 'leather',
  },
  {
    id: 'feather',
    name: 'Feather',
    description: 'Bird feather. Used for arrows.',
    type: 'material',
    rarity: 'common',
    sellPrice: 2,
    stackable: true,
    maxStack: 64,
    icon: 'feather',
  },
  {
    id: 'bone',
    name: 'Bone',
    description: 'Skeleton remains. Used for bone meal.',
    type: 'material',
    rarity: 'common',
    sellPrice: 3,
    stackable: true,
    maxStack: 64,
    icon: 'bone',
  },
  {
    id: 'slime_ball',
    name: 'Slime Ball',
    description: 'Gooey substance. Bouncy!',
    type: 'material',
    rarity: 'uncommon',
    sellPrice: 10,
    stackable: true,
    maxStack: 64,
    icon: 'slime_ball',
  },
  {
    id: 'ender_pearl',
    name: 'Ender Pearl',
    description: 'Mysterious pearl. Allows teleportation.',
    type: 'material',
    rarity: 'rare',
    sellPrice: 25,
    stackable: true,
    maxStack: 16,
    icon: 'ender_pearl',
  },
  {
    id: 'blaze_rod',
    name: 'Blaze Rod',
    description: 'Blazing rod from the Nether.',
    type: 'material',
    rarity: 'rare',
    sellPrice: 30,
    stackable: true,
    maxStack: 64,
    icon: 'blaze_rod',
  },
  {
    id: 'nether_star',
    name: 'Nether Star',
    description: 'Dropped by the Wither. Immensely powerful.',
    type: 'material',
    rarity: 'mythic',
    sellPrice: 10000,
    stackable: true,
    maxStack: 1,
    icon: 'nether_star',
  },
];
