import { ItemDefinition } from "../gameTypes";

export const MATERIAL_ITEMS: ItemDefinition[] = [
  {
    id: "stick",
    name: "Stick",
    description: "Wooden stick. Basic crafting component.",
    type: "material",
    rarity: "common",
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: "stick.png",
    recipe: {
      resultQuantity: 4,
      ingredients: [{ itemId: "oak_planks", quantity: 2 }],
      craftTime: 1000,
      category: "materials",
    },
  },
  {
    id: "flint",
    name: "Flint",
    description: "Sharp stone fragment. Used to make arrows and fire.",
    type: "material",
    rarity: "common",
    sellPrice: 2,
    stackable: true,
    maxStack: 64,
    icon: "flint.png",
  },
  {
    id: "string",
    name: "String",
    description: "Spider silk thread. Used for bows and fishing.",
    type: "material",
    rarity: "common",
    sellPrice: 3,
    stackable: true,
    maxStack: 64,
    icon: "string.png",
  },
  {
    id: "leather",
    name: "Leather",
    description: "Animal hide. Used for armor and books.",
    type: "material",
    rarity: "common",
    sellPrice: 5,
    stackable: true,
    maxStack: 64,
    icon: "leather.png",
  },
  {
    id: "feather",
    name: "Feather",
    description: "Bird feather. Used for arrows.",
    type: "material",
    rarity: "common",
    sellPrice: 2,
    stackable: true,
    maxStack: 64,
    icon: "feather.png",
  },
  {
    id: "bone",
    name: "Bone",
    description: "Skeleton remains. Used for bone meal.",
    type: "material",
    rarity: "common",
    sellPrice: 3,
    stackable: true,
    maxStack: 64,
    icon: "bone.png",
  },
  {
    id: "slime_ball",
    name: "Slime Ball",
    description: "Gooey substance. Bouncy!",
    type: "material",
    rarity: "uncommon",
    sellPrice: 10,
    stackable: true,
    maxStack: 64,
    icon: "slime_ball.png",
  },
  {
    id: "wheat",
    name: "Wheat",
    description: "Harvested crop. Used for making bread.",
    type: "material",
    rarity: "common",
    sellPrice: 1,
    stackable: true,
    maxStack: 64,
    icon: "wheat",
  },
];
