import { ItemDefinition } from '../gameTypes';

export const MINERAL_ITEMS: ItemDefinition[] = [
  {
    id: 'coal',
    name: 'Coal',
    description: 'Black combustible rock. Used as fuel.',
    type: 'mineral',
    rarity: 'common',
    sellPrice: 5,
    stackable: true,
    maxStack: 64,
    icon: 'coal',
  },
  {
    id: 'iron_ore',
    name: 'Iron Ore',
    description: 'Raw iron ore. Smelt it to get iron ingots.',
    type: 'mineral',
    rarity: 'common',
    sellPrice: 8,
    stackable: true,
    maxStack: 64,
    icon: 'iron_ore',
  },
  {
    id: 'iron_ingot',
    name: 'Iron Ingot',
    description: 'Refined iron. Essential crafting material.',
    type: 'mineral',
    rarity: 'uncommon',
    sellPrice: 15,
    stackable: true,
    maxStack: 64,
    icon: 'iron_ingot',
  },
  {
    id: 'gold_ore',
    name: 'Gold Ore',
    description: 'Raw gold ore. Shiny and valuable.',
    type: 'mineral',
    rarity: 'uncommon',
    sellPrice: 20,
    stackable: true,
    maxStack: 64,
    icon: 'gold_ore',
  },
  {
    id: 'gold_ingot',
    name: 'Gold Ingot',
    description: 'Pure gold bar. Highly valuable.',
    type: 'mineral',
    rarity: 'rare',
    sellPrice: 40,
    stackable: true,
    maxStack: 64,
    icon: 'gold_ingot',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    description: 'Precious gemstone. The hardest material.',
    type: 'mineral',
    rarity: 'epic',
    sellPrice: 100,
    stackable: true,
    maxStack: 64,
    icon: 'diamond',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    description: 'Rare green gem. Used for trading.',
    type: 'mineral',
    rarity: 'epic',
    sellPrice: 150,
    stackable: true,
    maxStack: 64,
    icon: 'emerald',
  },
  {
    id: 'netherite_ingot',
    name: 'Netherite Ingot',
    description: 'Ancient debris refined. Ultimate material.',
    type: 'mineral',
    rarity: 'legendary',
    sellPrice: 500,
    stackable: true,
    maxStack: 64,
    icon: 'netherite_ingot',
  },
];
