import { ItemDefinition } from '../gameTypes';

export const POTION_ITEMS: ItemDefinition[] = [
  {
    id: 'potion_healing',
    name: 'Potion of Healing',
    description: 'Instantly restores health.',
    type: 'potion',
    rarity: 'uncommon',
    sellPrice: 20,
    stackable: true,
    maxStack: 16,
    icon: 'potion_healing',
    stats: { instant_health: 4 },
  },
  {
    id: 'potion_speed',
    name: 'Potion of Swiftness',
    description: 'Increases movement speed.',
    type: 'potion',
    rarity: 'uncommon',
    sellPrice: 25,
    stackable: true,
    maxStack: 16,
    icon: 'potion_speed',
    stats: { speed_boost: 20, duration: 180 },
  },
  {
    id: 'potion_strength',
    name: 'Potion of Strength',
    description: 'Increases attack damage.',
    type: 'potion',
    rarity: 'rare',
    sellPrice: 40,
    stackable: true,
    maxStack: 16,
    icon: 'potion_strength',
    stats: { damage_boost: 3, duration: 180 },
  },
  {
    id: 'potion_regeneration',
    name: 'Potion of Regeneration',
    description: 'Slowly restores health over time.',
    type: 'potion',
    rarity: 'rare',
    sellPrice: 50,
    stackable: true,
    maxStack: 16,
    icon: 'potion_regeneration',
    stats: { regeneration: 1, duration: 45 },
  },
  {
    id: 'potion_fire_resistance',
    name: 'Potion of Fire Resistance',
    description: 'Immunity to fire and lava damage.',
    type: 'potion',
    rarity: 'rare',
    sellPrice: 45,
    stackable: true,
    maxStack: 16,
    icon: 'potion_fire_resistance',
    stats: { fire_resistance: 1, duration: 180 },
  },
  {
    id: 'potion_invisibility',
    name: 'Potion of Invisibility',
    description: 'Become completely invisible.',
    type: 'potion',
    rarity: 'epic',
    sellPrice: 80,
    stackable: true,
    maxStack: 16,
    icon: 'potion_invisibility',
    stats: { invisibility: 1, duration: 180 },
  },
];
