import { ItemDefinition } from "../gameTypes";

export const SEED_ITEMS: ItemDefinition[] = [
  {
    id: "wheat_seeds",
    name: "Wheat Seeds",
    description: "Plant these to grow wheat. Takes 5 minutes to fully mature.",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
    stackable: true,
    maxStack: 999,
    icon: "wheat_seed.png",
    plantedIcon: "planted.png",
    grownIcon: "wheat.png",
    growthTime: 300,
    harvestYield: { min: 1, max: 3 },
    cropItemId: "wheat",
  },
  {
    id: "carrot_seeds",
    name: "Carrot Seeds",
    description:
      "Plant these to grow carrots. Takes 8 minutes to fully mature.",
    type: "seed",
    rarity: "common",
    sellPrice: 10,
    stackable: true,
    maxStack: 999,
    icon: "carrot_seed.png",
    plantedIcon: "planted.png",
    grownIcon: "carrot.png",
    growthTime: 480,
    harvestYield: { min: 2, max: 4 },
    cropItemId: "carrot",
  },
  {
    id: "potato_seeds",
    name: "Potato Seeds",
    description:
      "Plant these to grow potatoes. Takes 10 minutes to fully mature.",
    type: "seed",
    rarity: "common",
    sellPrice: 15,
    stackable: true,
    maxStack: 999,
    icon: "potato_seed.png",
    plantedIcon: "planted.png",
    grownIcon: "potato.png",
    growthTime: 600,
    harvestYield: { min: 2, max: 5 },
    cropItemId: "potato",
  },
  {
    id: "melon_seeds",
    name: "Melon Seeds",
    description:
      "Plant these to grow melons. Takes 15 minutes to fully mature.",
    type: "seed",
    rarity: "uncommon",
    sellPrice: 25,
    stackable: true,
    maxStack: 999,
    icon: "melon_seeds",
    plantedIcon: "melon_planted",
    grownIcon: "melon_grown",
    growthTime: 900,
    harvestYield: { min: 3, max: 6 },
    cropItemId: "melon_slice",
  },
  {
    id: "pumpkin_seeds",
    name: "Pumpkin Seeds",
    description:
      "Plant these to grow pumpkins. Takes 20 minutes to fully mature.",
    type: "seed",
    rarity: "uncommon",
    sellPrice: 30,
    stackable: true,
    maxStack: 999,
    icon: "pumpkin_seeds",
    plantedIcon: "pumpkin_planted",
    grownIcon: "pumpkin_grown",
    growthTime: 1200,
    harvestYield: { min: 1, max: 2 },
    cropItemId: "pumpkin",
  },
  {
    id: "beetroot_seeds",
    name: "Beetroot Seeds",
    description:
      "Plant these to grow beetroot. Takes 12 minutes to fully mature.",
    type: "seed",
    rarity: "common",
    sellPrice: 20,
    stackable: true,
    maxStack: 999,
    icon: "beetroot_seeds",
    plantedIcon: "beetroot_planted",
    grownIcon: "beetroot_grown",
    growthTime: 720,
    harvestYield: { min: 1, max: 3 },
    cropItemId: "beetroot",
  },
];

export const CROP_ITEMS: ItemDefinition[] = [
  {
    id: "wheat",
    name: "Wheat",
    description: "Harvested wheat. Can be sold or used for crafting.",
    type: "food",
    isCrop: true,
    rarity: "common",
    sellPrice: 15,
    stackable: true,
    maxStack: 999,
    icon: "wheat.png",
    stats: { hunger: 1, saturation: 0.6 },
  },
  {
    id: "carrot",
    name: "Carrot",
    description: "A fresh orange carrot. Can be sold or eaten.",
    type: "food",
    isCrop: true,
    rarity: "common",
    sellPrice: 25,
    stackable: true,
    maxStack: 999,
    icon: "carrot.png",
    stats: { hunger: 3, saturation: 3.6 },
  },
  {
    id: "potato",
    name: "Potato",
    description: "A fresh potato. Can be sold or cooked.",
    type: "food",
    isCrop: true,
    rarity: "common",
    sellPrice: 35,
    stackable: true,
    maxStack: 999,
    icon: "potato.png",
    stats: { hunger: 1, saturation: 0.6 },
  },
  {
    id: "melon_slice",
    name: "Melon Slice",
    description: "A juicy melon slice. Can be sold or eaten.",
    type: "food",
    isCrop: true,
    rarity: "uncommon",
    sellPrice: 50,
    stackable: true,
    maxStack: 999,
    icon: "melon_slice",
    stats: { hunger: 2, saturation: 1.2 },
  },
  {
    id: "pumpkin",
    name: "Pumpkin",
    description: "A large orange pumpkin. Can be sold or used for crafting.",
    type: "food",
    isCrop: true,
    rarity: "uncommon",
    sellPrice: 75,
    stackable: true,
    maxStack: 999,
    icon: "pumpkin",
    stats: { hunger: 2, saturation: 1.2 },
  },
  {
    id: "beetroot",
    name: "Beetroot",
    description: "A deep red beetroot. Can be sold or eaten.",
    type: "food",
    isCrop: true,
    rarity: "common",
    sellPrice: 45,
    stackable: true,
    maxStack: 999,
    icon: "beetroot",
    stats: { hunger: 1, saturation: 1.2 },
  },
];
