import { ItemDefinition } from '../gameTypes';

export const SPECIAL_ITEMS: ItemDefinition[] = [
  {
    id: 'winter_pickaxe',
    name: 'Frostbite Pickaxe',
    description: 'An enchanted pickaxe forged from eternal ice. Glows with ancient power.',
    type: 'tool',
    rarity: 'legendary',
    sellPrice: 2500,
    stackable: false,
    maxStack: 1,
    icon: 'diamond_pickaxe',
    toolType: 'pickaxe',
    stats: { mining_speed: 12, durability: 3000 },
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'void_crystal',
    name: 'Void Crystal',
    description: 'A fragment of pure darkness. Radiates mysterious energy.',
    type: 'material',
    rarity: 'mythic',
    sellPrice: 15000,
    stackable: true,
    maxStack: 16,
    icon: 'ender_pearl',
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'phoenix_feather',
    name: 'Phoenix Feather',
    description: 'A rare feather from the legendary phoenix. Burns with eternal flame.',
    type: 'material',
    rarity: 'legendary',
    sellPrice: 5000,
    stackable: true,
    maxStack: 16,
    icon: 'feather',
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'dragons_breath',
    name: "Dragon's Breath",
    description: 'Bottled essence of dragon fire. Extremely volatile.',
    type: 'potion',
    rarity: 'legendary',
    sellPrice: 3000,
    stackable: true,
    maxStack: 8,
    icon: 'potion_fire_resistance',
    stats: { fire_damage: 20, duration: 300 },
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'celestial_armor',
    name: 'Celestial Chestplate',
    description: 'Armor blessed by the stars. Provides divine protection.',
    type: 'armor',
    rarity: 'mythic',
    sellPrice: 25000,
    stackable: false,
    maxStack: 1,
    icon: 'netherite_chestplate',
    armorSlot: 'chestplate',
    stats: { armor: 12, toughness: 5, knockback_resistance: 2, durability: 1000 },
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'soul_gem',
    name: 'Soul Gem',
    description: 'Contains the trapped essence of a powerful entity.',
    type: 'material',
    rarity: 'epic',
    sellPrice: 2000,
    stackable: true,
    maxStack: 16,
    icon: 'diamond',
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'enchanted_obsidian',
    name: 'Enchanted Obsidian',
    description: 'Obsidian infused with magical energy. Pulses with power.',
    type: 'block',
    rarity: 'epic',
    sellPrice: 200,
    stackable: true,
    maxStack: 64,
    icon: 'obsidian',
    isSpecial: true,
    isEnchanted: true,
  },
  {
    id: 'ambrosia',
    name: 'Ambrosia',
    description: 'Food of the gods. Grants temporary invincibility.',
    type: 'food',
    rarity: 'mythic',
    sellPrice: 10000,
    stackable: true,
    maxStack: 8,
    icon: 'enchanted_golden_apple',
    stats: { hunger: 10, saturation: 20, absorption: 8, regeneration: 5, resistance: 3 },
    isSpecial: true,
    isEnchanted: true,
  },
];
