import { ItemDefinition } from "../gameTypes";

export const TOOL_ITEMS: ItemDefinition[] = [
  {
    id: "wooden_pickaxe",
    name: "Wooden Pickaxe",
    description: "Basic mining tool. Gets the job done.",
    type: "tool",
    rarity: "common",
    sellPrice: 5,
    stackable: false,
    maxStack: 1,
    icon: "wooden_pick.png",
    toolType: "pickaxe",
    stats: { mining_speed: 2, durability: 59 },
  },
  {
    id: "stone_pickaxe",
    name: "Stone Pickaxe",
    description: "Upgraded mining tool. More durable.",
    type: "tool",
    rarity: "common",
    sellPrice: 10,
    stackable: false,
    maxStack: 1,
    icon: "stone_pick.png",
    toolType: "pickaxe",
    stats: { mining_speed: 4, durability: 131 },
  },
  {
    id: "iron_pickaxe",
    name: "Iron Pickaxe",
    description: "Reliable iron tool. Can mine gold and diamonds.",
    type: "tool",
    rarity: "uncommon",
    sellPrice: 30,
    stackable: false,
    maxStack: 1,
    icon: "iron_pick.png",
    toolType: "pickaxe",
    stats: { mining_speed: 6, durability: 250 },
  },
  {
    id: "diamond_pickaxe",
    name: "Diamond Pickaxe",
    description: "Premium mining tool. Can mine obsidian.",
    type: "tool",
    rarity: "epic",
    sellPrice: 200,
    stackable: false,
    maxStack: 1,
    icon: "diamond_pick.png",
    toolType: "pickaxe",
    stats: { mining_speed: 8, durability: 1561 },
  },
  {
    id: "netherite_pickaxe",
    name: "Netherite Pickaxe",
    description: "Ultimate mining tool. Indestructible.",
    type: "tool",
    rarity: "legendary",
    sellPrice: 1000,
    stackable: false,
    maxStack: 1,
    icon: "netherite_pick.png",
    toolType: "pickaxe",
    stats: { mining_speed: 9, durability: 2031 },
  },
  {
    id: "wooden_sword",
    name: "Wooden Sword",
    description: "Better than nothing.",
    type: "tool",
    rarity: "uncommon",
    sellPrice: 5,
    stackable: false,
    maxStack: 1,
    icon: "wooden_sword.png",
    toolType: "sword",
    stats: { attack_damage: 3, attack_speed: 2, durability: 105 },
  },
  {
    id: "stone_sword",
    name: "Stone Sword",
    description: "Better than nothing, and a wooden sword.",
    type: "tool",
    rarity: "uncommon",
    sellPrice: 7,
    stackable: false,
    maxStack: 1,
    icon: "stone_sword.png",
    toolType: "sword",
    stats: { attack_damage: 5, attack_speed: 1.8, durability: 145 },
  },
  {
    id: "iron_sword",
    name: "Iron Sword",
    description: "Standard combat weapon.",
    type: "tool",
    rarity: "uncommon",
    sellPrice: 25,
    stackable: false,
    maxStack: 1,
    icon: "iron_sword.png",
    toolType: "sword",
    stats: { attack_damage: 6, attack_speed: 1.6, durability: 250 },
  },
  {
    id: "diamond_sword",
    name: "Diamond Sword",
    description: "Powerful diamond blade.",
    type: "tool",
    rarity: "epic",
    sellPrice: 180,
    stackable: false,
    maxStack: 1,
    icon: "diamond_sword.png",
    toolType: "sword",
    stats: { attack_damage: 7, attack_speed: 1.6, durability: 1561 },
  },
  {
    id: "iron_axe",
    name: "Iron Axe",
    description: "Versatile chopping tool.",
    type: "tool",
    rarity: "uncommon",
    sellPrice: 28,
    stackable: false,
    maxStack: 1,
    icon: "iron_axe",
    toolType: "axe",
    stats: { chopping_speed: 6, attack_damage: 9, durability: 250 },
  },
  {
    id: "watering_can",
    name: "Watering Can",
    description: "Water your crops to help them grow faster. Essential farming tool.",
    type: "tool",
    rarity: "common",
    sellPrice: 25,
    stackable: false,
    maxStack: 1,
    icon: "watering_can",
    toolType: "watering_can",
    stats: { water_capacity: 10, durability: 500 },
  },
];
